/// Flutter icons SocialsIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SocialsIcons
///      fonts:
///       - asset: fonts/SocialsIcons.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class SocialIcons {
  SocialIcons._();

  static const _kFontFam = 'SocialsIcons';

  static const IconData twitter = IconData(0xf099, fontFamily: _kFontFam);
  static const IconData facebook = IconData(0xf09a, fontFamily: _kFontFam);
  static const IconData instagram = IconData(0xf16d, fontFamily: _kFontFam);
}
